name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Checkout
      - name: List Files after checkout
        run: |
          pwd
          ls
        uses: actions/checkout@v1
      - name: simple JS Actions
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo"${{ steps.greet.outputs.time }}"
