name: Actions Workflow

on: 
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files one
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GUTHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files after checkout
        run: |
          pwd
          ls
      - name: simple JS Actions
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo"${{ steps.greet.outputs.time }}"
